# baseURL = "https://estherkim99.github.io/pandam"
# baseURL = "http://127.0.0.1:5500/public"
baseURL = "https://pandam-magaizine.heroku.com"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Esther Kim"
title = "PanDam Amsterdam"
relativeurls = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true