baseURL = "https://estherkim99.github.io/pandam/public"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Esther Kim"
title = "PanDam Amsterdam"
relativeurls = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true